### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by RegexMC** [builder-247/node-autotip#7] opened 2020-04-13 03:46 UTC
hastebin is broken so just pasting the error here ;/

C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\node_modules\minecraft-protocol\src\transforms\framing.js:66
          } else { throw e }
                   ^

TypeError: Cannot read property 'value' of undefined
    at getHoverData (C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\index.js:40:34)
    at Bot.bot.on (C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\index.js:103:17)
    at Bot.emit (events.js:182:13)
    at Client.bot._client.on (C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\node_modules\mineflayer\lib\plugins\chat.js:55:9)
    at Client.emit (events.js:182:13)
    at FullPacketParser.deserializer.on (C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\node_modules\minecraft-protocol\src\client.js:82:12)
    at FullPacketParser.emit (events.js:182:13)
    at addChunk (C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:297:12)
    at readableAddChunk (C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:11)
    at FullPacketParser.Readable.push (C:\Users\david\Desktop\Downloads\node-autotip-master (1)\node-autotip-master\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:240:10)

**Comment by builder-247** [comment] 2020-04-13 11:36
When does this occur? Instantly on startup or randomly?

**Comment by RegexMC** [comment] 2020-04-13 12:02
> When does this occur? Instantly on startup or randomly?

usually after a few mins
it never happens immediately, but then the time it takes is random.

**Comment by builder-247** [comment] 2020-04-14 12:33
I'm unable to reproduce this, have you tried a clean install?

**Comment by builder-247** [comment] 2020-09-05 10:21
Closing this for now - if the issue is encountered just comment below.

**Closed by builder-247** 2020-09-05 10:21 UTC
Labels: question
